-- JR Electricidad V3 — Notification center
CREATE TABLE IF NOT EXISTS notification_preferences (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  quote_requests TINYINT(1) NOT NULL DEFAULT 1,
  quote_status TINYINT(1) NOT NULL DEFAULT 1,
  jobs TINYINT(1) NOT NULL DEFAULT 1,
  payments TINYINT(1) NOT NULL DEFAULT 1,
  system TINYINT(1) NOT NULL DEFAULT 1,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO notification_preferences (id)
VALUES (1)
ON DUPLICATE KEY UPDATE id=id;